#!/usr/bin/env python2

import sys
try:
    import monorail.ai
except ImportError:
    print "Error: ai module not present. Run 'make' first!"
    sys.exit(1)
import monorail.monorail

monorail.monorail.main()
